/* ============================================================
   maltiplata — TOPIC REGISTRY (single source of truth)
   Add a topic here → it appears on /topics/ and the homepage.
   Set ready:true only once the .html page exists, otherwise the
   card shows "coming soon" and isn't clickable (no 404s, ever).
   ============================================================ */
window.MALTI_TOPICS = [
  /* ---- build your own thing ---- */
  { slug:"trademark-your-name", emoji:"®️", title:"how to trademark your name", cat:"build",
    featured:true, ready:true,
    blurb:"the 2026 USPTO base fee is $350 per class — non-refundable. why the search matters more than the filing." },
  { slug:"start-an-etsy-shop", emoji:"🧵", title:"start an etsy shop (with the real numbers)", cat:"build",
    featured:true, ready:true,
    blurb:"etsy takes ~10% before ads, the median seller earns under $500/yr, and digital products carry 3x the margin. the honest setup guide." },
  { slug:"price-your-work", emoji:"🏷️", title:"what to charge (stop underpricing)", cat:"build",
    featured:false, ready:false,
    blurb:"hourly vs project vs value pricing, the number women most often undershoot, and how to raise rates on existing clients." },
  { slug:"get-paid-freelance", emoji:"🧾", title:"contracts & actually getting paid", cat:"build",
    featured:false, ready:false,
    blurb:"deposits, invoicing, and what to do when a client goes quiet. the boring paperwork that protects you." },
  { slug:"women-owned-certification", emoji:"🏅", title:"women-owned business certification", cat:"build",
    featured:false, ready:false,
    blurb:"WOSB, WBENC, and state certifications — what they unlock, what they cost, and whether they're worth the paperwork." },
  { slug:"creator-income", emoji:"📱", title:"getting paid on tiktok & instagram", cat:"build",
    featured:false, ready:false,
    blurb:"how creators actually make money — brand deals, affiliate, shop — and the follower counts that matter (less than you think)." },
  { slug:"sell-on-amazon", emoji:"📦", title:"selling on amazon, honestly", cat:"build",
    featured:false, ready:false,
    blurb:"FBA fees, referral fees, and the real startup cost — plus whether it's still worth entering in 2026." },
  { slug:"business-banking-books", emoji:"🏦", title:"business banking & bookkeeping basics", cat:"build",
    featured:false, ready:false,
    blurb:"separate accounts, what to track, and the receipts that become deductions. the habit that makes tax season boring." },
  { slug:"read-a-contract", emoji:"📜", title:"how to read a contract before you sign", cat:"build",
    featured:false, ready:false,
    blurb:"scope, payment, IP, termination — the clauses that actually matter and the ones people regret skipping." },

  { slug:"where-to-park-cash", emoji:"🏦", title:"where to park money you'll need soon", cat:"save",
    featured:true, ready:true,
    blurb:"savings, CD, treasury bill, or I bond? the answer is about when you need it back — not which pays most." },
  /* ---- caregiving & single-income households ---- */
  /* ---- taxes ---- */
  { slug:"freelance-taxes", emoji:"🧾", title:"1099 & freelance taxes", cat:"taxes",
    featured:true, ready:true,
    blurb:"nobody withholds tax on freelance income. the 15.3% surprise, the four dates, and why no 1099 doesn't mean no tax." },
  { slug:"w4-explained", emoji:"📄", title:"the w-4, explained", cat:"taxes",
    featured:true, ready:true,
    blurb:"the form you filled out on day one decides every paycheck since. why you owed, and why a big refund isn't a win." },
  { slug:"kids-and-taxes", emoji:"🧸", title:"kids & taxes", cat:"taxes",
    featured:true, ready:true,
    blurb:"$2,200 per child, a childcare credit that jumped to 50%, and a $7,500 FSA limit that moved for the first time since 1986." },
  { slug:"spousal-ira", emoji:"🌱", title:"the spousal ira", cat:"retirement",
    featured:true, ready:true,
    blurb:"no paycheck? you can still put $7,500 a year into a retirement account in your own name. almost nobody tells you this exists." },
  { slug:"head-of-household", emoji:"🧾", title:"head of household (single parents)", cat:"taxes",
    featured:false, ready:false,
    blurb:"the filing status single parents most often miss — a bigger standard deduction and better brackets than filing single." },
  { slug:"child-support-basics", emoji:"⚖️", title:"child support, actually explained", cat:"legal",
    featured:false, ready:false,
    blurb:"getting it ordered, getting it enforced, and how it’s taxed (it isn’t — but almost everyone assumes it is)." },
  { slug:"single-parent-safety-net", emoji:"🛟", title:"guardianship & life insurance when you’re the only parent", cat:"legal",
    featured:false, ready:false,
    blurb:"who raises them, and what they live on. the two documents that answer it, without the fear-mongering." },
  { slug:"403b-decoded", emoji:"🍎", title:"the 403(b) trap (teachers & nurses)", cat:"retirement",
    featured:false, ready:false,
    blurb:"your workplace plan may be full of high-fee annuities sold in the break room. how to find the low-cost option hiding in it." },
  { slug:"pslf-explained", emoji:"🎓", title:"pslf & income-driven repayment", cat:"debt",
    featured:false, ready:false,
    blurb:"public service loan forgiveness, the paperwork that actually counts, and the recertification that trips everyone." },
  { slug:"self-employed-health-insurance", emoji:"🩺", title:"health insurance when you work for yourself", cat:"insurance",
    featured:false, ready:false,
    blurb:"the marketplace, subsidies you probably qualify for, and the deduction that makes premiums cheaper." },
  { slug:"pinterest-traffic", emoji:"📌", title:"pinterest for your shop or side hustle", cat:"build",
    featured:false, ready:false,
    blurb:"it’s a search engine, not a feed — which is why pins keep working for years. how to use it to sell." },
  { slug:"grants-for-women", emoji:"🎯", title:"grants & funding for women founders", cat:"build",
    featured:false, ready:false,
    blurb:"women-owned businesses got 2.4% of venture capital. here’s the money that isn’t VC — grants, CDFIs, and microloans." },
  { slug:"military-spouse-money", emoji:"🎖️", title:"money for military spouses", cat:"work",
    featured:false, ready:false,
    blurb:"licenses that don’t transfer, forced career gaps, and the benefits and portable-career options built for this." },

  { slug:"self-employed-retirement", emoji:"🧑‍💻", title:"retirement when you work for yourself", cat:"retirement",
    featured:true, ready:true,
    blurb:"freelancers can shelter up to $72,000 a year. picking solo 401(k) over SEP IRA can be worth $24,000 more annually at ordinary incomes." },
  { slug:"down-payment-myth", emoji:"🏠", title:"the 20% down payment myth", cat:"life",
    featured:true, ready:true,
    blurb:"the median first-time buyer puts down about 10%. minimums are 3% conventional, 3.5% FHA, 0% VA — and waiting often costs more than PMI." },
  { slug:"equity-compensation", emoji:"📊", title:"rsus and the tax bill nobody warns you about", cat:"work",
    featured:true, ready:true,
    blurb:"your employer withholds a flat 22% on vesting stock. if you're in a higher bracket, the shortfall lands in april." },
  { slug:"great-wealth-transfer", emoji:"🎁", title:"$124 trillion is about to change hands", cat:"life",
    featured:true, ready:true,
    blurb:"women are expected to inherit roughly 70% of it. what to do in the first 90 days — and why receiving money isn't the same as having authority over it." },
  { slug:"crypto-honestly", emoji:"🪙", title:"do you need crypto? (honestly)", cat:"invest",
    featured:true, ready:true,
    blurb:"women hold less crypto than men and outperform them anyway. the honest answer on whether the gap is costing you anything." },

  { slug:"divorce-money-checklist", emoji:"📋", title:"the divorce money checklist", cat:"legal",
    featured:true, ready:true,
    blurb:"what to gather before you file, how retirement accounts actually split (QDROs), and the tax trap that costs people six figures." },
  { slug:"disability-insurance", emoji:"🩺", title:"the insurance nobody talks about", cat:"insurance",
    featured:true, ready:true,
    blurb:"1 in 4 of today's 20-year-olds will be out of work a year or more. this protects the asset everything else depends on: your income." },
  { slug:"hsa-stealth-retirement", emoji:"💊", title:"the account with three tax breaks", cat:"retirement",
    featured:true, ready:true,
    blurb:"an HSA is the only account with a triple tax advantage — and most people spend it like a debit card instead of investing it." },

  { slug:"financial-abuse", emoji:"🛡️", title:"when money is the leash", cat:"safety",
    featured:true, ready:true,
    blurb:"financial abuse appears in 99% of domestic violence cases and is the top reason people stay. what it looks like, and what you can do quietly." },
  { slug:"old-401k-rollover", emoji:"📦", title:"the 401(k) you left at an old job", cat:"retirement",
    featured:true, ready:true,
    blurb:"32 million forgotten accounts hold $2.1 trillion — about $66k each. how to find yours and move it without a tax bill." },
  { slug:"vet-a-financial-advisor", emoji:"🔍", title:"how to vet a financial advisor", cat:"work",
    featured:true, ready:true,
    blurb:"anyone can use the title. fiduciary vs suitability, fee-only vs fee-based, and the two free databases that tell you the truth." },

  { slug:"social-security-for-women", emoji:"🏛️", title:"social security, the part nobody tells you", cat:"retirement",
    featured:true, ready:true,
    blurb:"married 10 years? you may be able to claim on your ex's record — they don't have to know, and it doesn't reduce their check." },
  { slug:"caregiving-career-break", emoji:"🕰️", title:"the caregiving career break, priced", cat:"work",
    featured:true, ready:true,
    blurb:"what stepping back to care for kids or parents really costs over a lifetime — and the small moves that soften it." },
  { slug:"beneficiary-designations", emoji:"📄", title:"the form that overrides your will", cat:"legal",
    featured:true, ready:true,
    blurb:"an ex still named on your 401(k) can inherit it — even if the divorce decree says otherwise. fifteen minutes to fix." },

  { slug:"how-to-start-an-llc", emoji:"🏛️", title:"how to start an llc", cat:"legal",
    featured:true, ready:true,
    blurb:"the wall between your business and your savings. what it protects, what it really costs, and the six steps to file it yourself." },
  { slug:"how-to-build-credit", emoji:"💳", title:"how to build credit", cat:"credit",
    featured:true, ready:true,
    blurb:"credit in your own name, from scratch or from a low score. the levers that actually move the number." },
  { slug:"how-to-file-taxes", emoji:"🧾", title:"taxes, decoded", cat:"taxes",
    featured:true, ready:true,
    blurb:"w-2 vs 1099, the deductions you're leaving on the table, and how to stop fearing april." },
  { slug:"how-to-get-out-of-debt", emoji:"🔥", title:"how to get out of debt", cat:"debt",
    featured:true, ready:true,
    blurb:"snowball vs avalanche and a payoff date you can circle on a calendar.", href:"../guides/how-to-get-out-of-debt.html" },
  { slug:"start-investing", emoji:"📈", title:"start investing with $5", cat:"invest",
    featured:true, ready:true,
    blurb:"index funds, roth iras, and why starting small and early beats starting big and late." },
  { slug:"emergency-fund", emoji:"🛟", title:"build an emergency fund", cat:"save",
    featured:true, ready:true,
    blurb:"the boring account that changes how safe your whole life feels. how much, and where to keep it." },
  { slug:"how-to-negotiate-salary", emoji:"💬", title:"negotiate your salary", cat:"work",
    featured:false, ready:true,
    blurb:"the research, the script, and the number — how to ask without the spiral.", href:"../guides/how-to-negotiate-your-salary.html" },
  { slug:"prenup-101", emoji:"💍", title:"prenups & postnups", cat:"legal",
    featured:false, ready:true,
    blurb:"a fairness list you make while you still like each other. what it covers, what it costs." },
  { slug:"health-insurance", emoji:"🏥", title:"health insurance, decoded", cat:"insurance",
    featured:false, ready:true,
    blurb:"premium, deductible, copay, out-of-pocket max — in plain words, so you pick the right plan.", href:"../guides/health-insurance-decoded.html" },
  { slug:"first-apartment", emoji:"🔑", title:"your first apartment", cat:"life",
    featured:false, ready:true,
    blurb:"what you really need to earn, the deposit math, and the lease traps to dodge.", href:"../guides/your-first-apartment.html" },
  { slug:"student-loans", emoji:"🎓", title:"student loans, decoded", cat:"debt",
    featured:false, ready:true,
    blurb:"federal vs private, repayment plans, and the forgiveness that actually exists.", href:"../guides/student-loans-decoded.html" },
  { slug:"buying-a-car", emoji:"🚗", title:"buying your first car", cat:"life",
    featured:false, ready:true,
    blurb:"financing vs cash, the out-the-door price, and how not to overpay at the dealer.", href:"../guides/buying-your-first-car.html" }
];
